### ISSUE TITLE
Possible issue beginning with 1.3.4

### ISSUE THREAD

**Issue by jhemak** [mrk-its/homeassistant-blitzortung#105]
Hello, I have been seeing the below error in my logs, multiple times, for the past day.  The only thing I recall changing was installing 1.3.4 of this integration.  I am not 100% sure there is a connection, however I've tried bouncing between 1.3.3 and 1.3.4 today and when I do get the error it's always been with 1.3.4 installed.  I've never, so far, seen the error when running 1.3.3.  That said, I don't understand the error enough to know if there could be a link with this integration or if it's something completely unrelated.  Has anyone else seen this?

```
2024-05-22 19:07:37.822 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 504, in _async_callback_delayed_write
await self._async_handle_write_data()
File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 529, in _async_handle_write_data
await self._async_write_data(self.path, data)
File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 534, in _async_write_data
await self.hass.async_add_executor_job(self._write_data, self.path, data)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 541, in _write_data
data["data"] = data.pop("data_func")()
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/homeassistant/exposed_entities.py", line 390, in _data_to_save
"exposed_entities": {
^
RuntimeError: dictionary changed size during iteration
```

**Comment by mrk-its** [comment]
Thanks, will take a look on that later this week

**Comment by jhemak** [comment]
I ended up seeing the same behavior even when downgraded to 1.3.3 ... however it is intermittent.  I disabled the integration and have not seen any of these errors since then.  So, I am still inclined to think this integration is causing it, just not sure in which version it started now.  I'll provide an update if I learn anything more.  Thanks!

**Comment by jhemak** [comment]
Confirmed ... it's due to this integration.  I had it disabled for the past 48 hours and saw none of these errors.  Just enabled it during a thunderstorm here and started seeing the error above within a couple minutes.

**Comment by jhemak** [comment]
Still seeing this with 2024.7.  Any ideas?

**Comment by jhemak** [comment]
This continues to be an issue even on 2025.8.
