### ISSUE TITLE
Getting these errors in 0.117.0

### ISSUE THREAD

**Issue by DavidFW1960** [mrk-its/homeassistant-blitzortung#22]
```
2020-10-29 13:26:36 ERROR (MainThread) [homeassistant.components.geo_location] Error adding entities for domain geo_location with platform blitzortung
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 465, in _async_add_entity
    raise HomeAssistantError(f"Invalid entity id: {entity.entity_id}")
homeassistant.exceptions.HomeAssistantError: Invalid entity id: geo_location.lightning_strike_-33_204977_150_397838
2020-10-29 13:26:37 ERROR (MainThread) [homeassistant.components.geo_location] Error adding entities for domain geo_location with platform blitzortung
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 465, in _async_add_entity
    raise HomeAssistantError(f"Invalid entity id: {entity.entity_id}")
homeassistant.exceptions.HomeAssistantError: Invalid entity id: geo_location.lightning_strike_-33_214746_150_405975
2020-10-29 13:26:37 ERROR (MainThread) [homeassistant.components.geo_location] Error adding entities for domain geo_location with platform blitzortung
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 465, in _async_add_entity
    raise HomeAssistantError(f"Invalid entity id: {entity.entity_id}")
homeassistant.exceptions.HomeAssistantError: Invalid entity id: geo_location.lightning_strike_-33_188727_150_372167
2020-10-29 13:26:53 ERROR (MainThread) [homeassistant.components.geo_location] Error adding entities for domain geo_location with platform blitzortung
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 465, in _async_add_entity
    raise HomeAssistantError(f"Invalid entity id: {entity.entity_id}")
homeassistant.exceptions.HomeAssistantError: Invalid entity id: geo_location.lightning_strike_-33_652534_150_426996
2020-10-29 13:26:53 ERROR (MainThread) [homeassistant.components.geo_location] Error adding entities for domain geo_location with platform blitzortung
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 465, in _async_add_entity
    raise HomeAssistantError(f"Invalid entity id: {entity.entity_id}")
homeassistant.exceptions.HomeAssistantError: Invalid entity id: geo_location.lightning_strike_-33_670589_150_425384
```
I also seem to have a valid entity..

![image](https://user-images.githubusercontent.com/36390762/97520491-783bdf80-19ef-11eb-8ea3-0b67640e2224.png)

Added as an integration in the GUI..

**Comment by mrk-its** [comment]
Thanks for report, it should be fixed now!
