### ISSUE TITLE
Unable to remove unknown dispatcher / Task exception was never retrieved

### ISSUE THREAD

**Issue by AdmiralStipe** [mrk-its/homeassistant-blitzortung#60]
I've been seeing this error for a long time (but there weren't many lightnings in my area, so it was not that disturbing), but after last night's heavy storm my log is completely flooded with errors like this one: 

`2022-06-24 01:20:27 WARNING (MainThread) [homeassistant.helpers.dispatcher] Unable to remove unknown dispatcher <bound method BlitzortungEvent._delete_callback of <Entity Lightning Strike: 11.1>>
2022-06-24 01:20:27 WARNING (MainThread) [homeassistant.helpers.dispatcher] Unable to remove unknown dispatcher <bound method BlitzortungEvent._delete_callback of <Entity Lightning Strike: 10.4>>
2022-06-24 01:20:27 WARNING (MainThread) [homeassistant.helpers.dispatcher] Unable to remove unknown dispatcher <bound method BlitzortungEvent._delete_callback of <Entity Lightning Strike: 11.0>>
2022-06-24 01:20:27 WARNING (MainThread) [homeassistant.helpers.dispatcher] Unable to remove unknown dispatcher <bound method BlitzortungEvent._delete_callback of <Entity Lightning Strike: 9.9>>
2022-06-24 01:20:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in async_remove
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity geo_location.lightning_strike_d1bdf8bace0a5acebac5bea67c7ab81813dd42d7 async_remove called twice
2022-06-24 01:20:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in async_remove
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity geo_location.lightning_strike_a59aa47b0065943abb02bbb747da93791c602b4d async_remove called twice
2022-06-24 01:20:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in async_remove
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity geo_location.lightning_strike_ba4e9b0eef410178e498ddd61fe968be19f88268 async_remove called twice
2022-06-24 01:20:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in async_remove
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity geo_location.lightning_strike_202b54cb32f7a2d773e3ba0a0a75f43be036c609 async_remove called twice
2022-06-24 01:30:27 WARNING (MainThread) [homeassistant.helpers.dispatcher] Unable to remove unknown dispatcher <bound method BlitzortungEvent._delete_callback of <Entity Lightning Strike: 9.0>>
2022-06-24 01:30:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in async_remove
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity geo_location.lightning_strike_69d9b680565a44fc0412ad2fd50981eb842cbee4 async_remove called twice
2022-06-24 01:32:27 WARNING (MainThread) [homeassistant.helpers.dispatcher] Unable to remove unknown dispatcher <bound method BlitzortungEvent._delete_callback of <Entity Lightning Strike: 7.7>>
2022-06-24 01:32:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in async_remove
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity geo_location.lightning_strike_adb44db53ec6665bdfed5750e551c79ebb612f6f async_remove called twice`

I saw an issue on the same matter already closed, but obviously the solution was not successfull. Can you please do something about it?

**Comment by AdmiralStipe** [comment]
Any feedback on this (from the author or someone else)? Or am I the only one having this issue?

**Comment by Larx** [comment]
Me too. In addition, my log is also flooded with entries like 
```
Jul 30 15:53:00 server conmon[198500]: homeassistant.exceptions.HomeAssistantError: Entity geo_location.lightning_strike_aa8e8762701f86f1951c39f8e3b3c18708792493 async_remove called twice
Jul 30 16:00:02 server conmon[198500]: 2022-07-30 16:00:02 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_d159ada5e7f3c69ee93481f36536eec2d09f912d

```
This integration currently seems to be a bit log-intensive ;-).

**Comment by stalakerob** [comment]
Same here.
