### ISSUE TITLE
non-threadsafe calls

### ISSUE THREAD

**Issue by Mariusthvdb** [mrk-its/homeassistant-blitzortung#85]
```
2024-02-27 10:18:03.610 ERROR (SyncWorker_6) [homeassistant.util.logging] Exception in _on_connection_change when dispatching 'blitzortung_mqtt_connected': ()
Traceback (most recent call last):
  File "/config/custom_components/blitzortung/__init__.py", line 222, in _on_connection_change
    sensor.async_write_ha_state()
```

as found while using debugy with BDraco trying to eliminate issues in the HA startup sequence

using 2024.3.0.dev20240227 and Blitzortung 1.3.1

please have a look, thanks

**Comment by Mariusthvdb** [comment]
adding to the above:
```
Logger: homeassistant.util.logging
Bron: util/logging.py:102
First occurred: 16:27:42 (1 gebeurtenissen)
Laatst gelogd: 16:27:42

Exception in _on_connection_change when dispatching 'blitzortung_mqtt_connected': () Traceback (most recent call last): File "/config/custom_components/blitzortung/__init__.py", line 222, in _on_connection_change sensor.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1175, in _async_write_ha_state hass.states.async_set( File "/usr/src/homeassistant/homeassistant/core.py", line 1964, in async_set self._bus.async_fire( File "/usr/src/homeassistant/homeassistant/core.py", line 1290, in async_fire self._hass.async_add_hass_job(job, event) File "/usr/src/homeassistant/homeassistant/core.py", line 603, in async_add_hass_job task = self.loop.create_task(hassjob.target(*args), name=hassjob.name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/asyncio/base_events.py", line 457, in create_task task = tasks.Task(coro, loop=self, name=name, context=context) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/asyncio/base_events.py", line 795, in call_soon self._check_thread() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 832, in _check_thread raise RuntimeError( RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```

**Comment by mrk-its** [comment]
I hope it is fixed by https://github.com/mrk-its/homeassistant-blitzortung/commit/f9021aac8383e6ce4798f1f206b5b96c9da41463, can you check?

**Comment by Mariusthvdb** [comment]
thanks I will, and report back

**Comment by bdraco** [comment]
The import executor is single threaded so 9.36s might just mean there was a line at the time.  You would need to test with only a single integration enabled to get the actual import time

**Comment by bdraco** [comment]
For the non thread safe operations, make sure you don’t use the async API from a thread.

For example if you need to create a task in the event loop from a thread, call hass.create_task and not hass.async_create_task as while the async call is faster it is only safe to do when running in the main thread / event loop

**Comment by andrewjswan** [comment]
> I hope it is fixed now, can you check current version?

```
2024-04-22 03:00:09.763 INFO (Thread-11 (_thread_main)) [custom_components.blitzortung.mqtt] Disconnected from MQTT server blitzortung.ha.sed.pl:1883 (7)
2024-04-22 03:00:09.983 ERROR (SyncWorker_19) [homeassistant.util.logging] Exception in _on_connection_change when dispatching 'blitzortung_mqtt_disconnected': ()
Traceback (most recent call last):
  File "/config/custom_components/blitzortung/__init__.py", line 222, in _on_connection_change
    sensor.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1181, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2181, in async_set
    self._bus._async_fire(  # pylint: disable=protected-access
  File "/usr/src/homeassistant/homeassistant/core.py", line 1459, in _async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 690, in async_add_hass_job
    self.loop.call_soon(hassjob.target, *args)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 832, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one

2024-04-22 03:00:09.983 ERROR (SyncWorker_21) [homeassistant.util.logging] Exception in _on_connection_change when dispatching 'blitzortung_mqtt_disconnected': ()
Traceback (most recent call last):
  File "/config/custom_components/blitzortung/__init__.py", line 222, in _on_connection_change
    sensor.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1181, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2181, in async_set
    self._bus._async_fire(  # pylint: disable=protected-access
  File "/usr/src/homeassistant/homeassistant/core.py", line 1459, in _async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 690, in async_add_hass_job
    self.loop.call_soon(hassjob.target, *args)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 832, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one

2024-04-22 03:00:09.985 ERROR (SyncWorker_56) [homeassistant.util.logging] Exception in _on_connection_change when dispatching 'blitzortung_mqtt_disconnected': ()
Traceback (most recent call last):
  File "/config/custom_components/blitzortung/__init__.py", line 222, in _on_connection_change
    sensor.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1181, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2181, in async_set
    self._bus._async_fire(  # pylint: disable=protected-access
  File "/usr/src/homeassistant/homeassistant/core.py", line 1459, in _async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 690, in async_add_hass_job
    self.loop.call_soon(hassjob.target, *args)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 832, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one

2024-04-22 03:00:09.986 ERROR (SyncWorker_55) [homeassistant.util.logging] Exception in _on_connection_change when dispatching 'blitzortung_mqtt_disconnected': ()
Traceback (most recent call last):
  File "/config/custom_components/blitzortung/__init__.py", line 222, in _on_connection_change
    sensor.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1181, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2181, in async_set
    self._bus._async_fire(  # pylint: disable=protected-access
  File "/usr/src/homeassistant/homeassistant/core.py", line 1459, in _async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 690, in async_add_hass_job
    self.loop.call_soon(hassjob.target, *args)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 832, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```

**Comment by bdraco** [comment]
```diff
diff --git a/custom_components/blitzortung/__init__.py b/custom_components/blitzortung/__init__.py
index d56cc39..a842df4 100644
--- a/custom_components/blitzortung/__init__.py
+++ b/custom_components/blitzortung/__init__.py
@@ -10,7 +10,7 @@ import voluptuous as vol
 from homeassistant.components.sensor import SensorDeviceClass
 from homeassistant.config_entries import ConfigEntry
 from homeassistant.const import CONF_LATITUDE, CONF_LONGITUDE, CONF_NAME, UnitOfLength
-from homeassistant.core import HomeAssistant
+from homeassistant.core import core, HomeAssistant
 from homeassistant.helpers.dispatcher import async_dispatcher_connect
 from homeassistant.helpers.event import async_track_time_interval
 
@@ -215,6 +215,7 @@ class BlitzortungCoordinator:
             )
         )
 
+    @callback
     def _on_connection_change(self, *args, **kwargs):
         if self.unloading:
             return
```

That should fix the issue reported above

**Comment by Mariusthvdb** [comment]
did you get it to work with that @andrewjswan ? I edited the init but entities remain unavailable to me

**Comment by andrewjswan** [comment]
> did you get it to work with that @andrewjswan ? I edited the init but entities remain unavailable to me

Fixed it, restarted the HA, there are sensors, but the value is `unknown` because no lightning.

**Comment by Mariusthvdb** [comment]
odd, thats what I did too..

where do we add the:
```
    @callback
    def _on_connection_change(self, *args, **kwargs):
        if self.unloading:
            return
```
? I might have put it erroneously before the 2 @property definitions in that case

**Comment by andrewjswan** [comment]
> odd, thats what I did too..

Don't forget to change?
```
from homeassistant.core import HomeAssistant
```
to
```
from homeassistant.core import callback, HomeAssistant
```

**Comment by andrewjswan** [comment]
> where do we add the:

I add `@callback` in 218 line before `def _on_connection_change(self, *args, **kwargs):`

**Comment by Mariusthvdb** [comment]
Right that did it, I completely overlooked that spot in Nicks suggestion, and, that we only had to add the `@callback`.

I now am seeing this again:

<img width="651" alt="Scherm­afbeelding 2024-05-01 om 16 21 31" src="https://github.com/mrk-its/homeassistant-blitzortung/assets/33354141/e5951f42-9ae4-4b3b-89d4-3b890ffae19d">

so at least we have progress ;-)
thanks to the both of you

**Comment by Mariusthvdb** [comment]
now if we get the probably easy fix for the deprecated typing alias, we could keep using this integration probably without all of the warnings:

https://developers.home-assistant.io/blog/2024/04/08/deprecated-backports-and-typing-aliases

in mqtt.py

**Comment by mathieucarbou** [comment]
Hello,
I got the issue today after HA update, applied the diff above and restarted.
It works now.
Thanks!

**Comment by mrk-its** [comment]
New version 1.3.3 released with your fixes. Thanks!
